DX-52829: Fix of java.lang.NoClassDefFoundError
if CSE_KMS is enabled DefaultS3ClientFactory is creating S3Client using  buildAmazonS3EncryptionClient, which is causing the issue as java.lang.NoClassDefFoundError: com/amazonaws/services/s3/AmazonS3EncryptionClientV2Builder.

Change-Id: I3ca362f9355fdf8ef77dd35683dd5ca8c0497d44