YARN-8856. TestTimelineReaderWebServicesHBaseStorage tests failing with NoClassDefFoundError. Contributed by Sushil Ks.
(cherry picked from commit eeaf8edaa7d36715dfa00a29fe46e4c6de4b98cf)

Change-Id: I579d26ef14f41ac6233be29f652410f5784bfd52